server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Swagger UI
springdoc:
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html
    displayRequestDuration: true
    operationsSorter: method
    tagsSorter: alpha
  default-produces-media-type: application/json